# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Publish

on:
  release:
    types: [prereleased, released]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup versions
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: :updateVersions
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Install Homebrew
        run: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      - name: Install Carthage
        run: brew install carthage
      - name: Publish
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: publish
        env:
          bintrayUsername: ${{ secrets.BINTRAY_USER }}
          bintrayKey: ${{ secrets.BINTRAY_KEY }}
